### ISSUE TITLE
Skip search results if query == only result

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-herd#165]
If there’s exactly one search result, and the query string is exactly the name of the only result (e. g. if you search for “ceylon.language”), I think it would be really convenient if you would skip the search results page and show the module page directly.

**Comment by FroMage** [comment]
Done.

**Comment by lucaswerkmeister** [comment]
I completely forgot that this was done and just got a very pleasant surprise :) thanks!
