### ISSUE TITLE
Links in module description broken

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-herd#208]
For example, go to https://modules.ceylon-lang.org/modules/ceylon.promise, then Expand the description and try to click on a link.

This is what the links look like:
```html
<a href="/repo/1/ceylon%2Fpromise%2F1.1.0%2Fmodule-doc%2Fapi%2FCompletable.type.html">Completable</a>
```
As you can see, all the slashes after the repository base were escaped to `%2F`.

This only happens in that description field. In the documentation for a specific module version, the links work fine. ([example](https://modules.ceylon-lang.org/modules/ceylon.promise/1.1.0/doc))

Found by Florian Gutmann ([ceylon-users thread](https://groups.google.com/d/msg/ceylon-users/Y806n_ZGf-U/4wsQ3owQJywJ)).

**Comment by FroMage** [comment]
Now the link works, but points to the current host instead of `modules.ceylon-lang.org`…

**Comment by FroMage** [comment]
Fixed.

**Comment by lucaswerkmeister** [comment]
Still points to the current host (`herd`) for me. I guess you haven’t deployed the update to the website yet?

**Comment by FroMage** [comment]
Yes, not deployed yet.
