### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-herd#216]
At http://design.jboss.org/ceylon/

**Comment by FroMage** [comment]
Done!

**Comment by gavinking** [comment]
Do you have 2x versions for HD displays?

**Comment by FroMage** [comment]
I can, but I've no idea how this works, and I can't test it. And it's not HD, my display is HD, what you're after is HiDPI ;)

**Comment by gavinking** [comment]
If you have the images in 2x, and if you can point me to the relevant bit of css, I can do it.

**Comment by FroMage** [comment]
They're not even CSS though, just plain `<img/>`, I think I recall they just need to exist with a special name, no?

**Comment by gavinking** [comment]
I believe you need to place the image using css, not using `<img/>`.

**Comment by FroMage** [comment]
It looks like you can do it for images too, I've tried, can you check that it works?

**Comment by gavinking** [comment]
@FroMage I got Herd running locally and it looks good to me.

**Comment by FroMage** [comment]
Excellent, thanks.
