### ISSUE TITLE
Error while deleting module with versions

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-herd#217]
```
PersistenceException occured : org.hibernate.exception.ConstraintViolationException: could not execute native bulk manipulation query in /app/models/Module.java (around line 316)
```

First deleting all versions followed by the module itself *does* work.

Edit: this was deleting `ceylon.formatter` byt the way, which has associated scripts, it might be related to that.

**Comment by FroMage** [comment]
Done.
