### ISSUE TITLE
Normalize `modulemember` database table

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-herd#219]
Stef, after applying my latest changes for #218 the Herd database will need to be updated because there's some erroneous data in it right now. 

The following two queries should fix them while my code fixes will hopefully prevent it from happening again:

    update modulemember set packagename=replace(packagename, '$', '');
    update modulemember set name=replace(name, '_.', '.');

**Comment by FroMage** [comment]
Fixed on live DB.
