### ISSUE TITLE
Be more strict about required JVM/JS implementations during upload

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-herd#225]
Now that we have ceylon/ceylon-spec#946 we can and should be more strict when verifying an upload:

 1. if the module descriptor does *not* have a `native` annotation it **must** have an implementation for both backends, if one of them is missing tell the developer to upload it or to mark his module native
 2. if the module descriptor *does* have a `native` annotation it **must** have a single implementation for that specific backend

**Comment by FroMage** [comment]
I think 1. would be annoying. Some users just want to care about one backend, and requiring them to add the `native` annotation forces them to care about the other.

I think 2. would indeed be nice.

**Comment by gavinking** [comment]
> Some users just want to care about one backend, and requiring them to add the `native` annotation forces them to care about the other.

And that's fine. Nobody's forcing them to care. But if they want to _share their module with others_ via Herd, I think it's reasonable to ask them to be explicit about what platforms it supports.

**Comment by quintesse** [comment]
True, but 1. could be solved with a quick-fix in the IDE making it far less annoying.
For example if we enforce this the problem with `ceylon.ast.core` not having a JS implementation because *they forgot* (!) would not have happened.

**Comment by FroMage** [comment]
> For example if we enforce this the problem with ceylon.ast.core not having a JS implementation because they forgot (!) would not have happened.

If he had read the existing warning… ;)

**Comment by FroMage** [comment]
So how does it work then when we add a new backend? Supposing I compile today for both JS and JVM I don't need `native`, but then one day we have a new backend and we still have to deal with modules not annotated `native` that were compiled at a time when only two backends existed, so they're still partial with no `native` annotation.

**Comment by quintesse** [comment]
True, that could be a problem, so maybe we should make 1. just a stronger message (maybe requiring a "yes, I know what I'm doing" second confirmation) and also give the explanation that using `native` could get rid of that message.

**Comment by luolong** [comment]
Well, cannot Herd itself figure out what is the target platform of the module that is being uploaded? Because right now, it is kind of self-evident from the artifact itself that is bering uploaded, what platform it runs on.

Now, I have nothing against warning the user if the `native` annotation is not present, but is it really necessary? Can't we just add the annotation implicitly in a compiler?

Looking at it another way -- the (model of a) module is an abstract idea on the source code level that has one or two (or more) concrete instantiations in the form of the compiled module -- one for each platform. Those instantiations are concrete artifacts and they only run on those concrete platforms. 

From this it follows that if I upload a `.car` archivce, I upload ceylon module instance that has been built for JVM. If I upload a `.js` file, it is clearly a ceylon module compiled for for JavaScript backend.

**Comment by quintesse** [comment]
@luolong sure, all you say is possible, but it sounds a bit like the eternal discussion between strong and loose typing "why specify that a variable is an integer when this is obvious from its contents?". Several of the reasons for strong typing hold here as well: I can *look* at the code and read the intentions without having to dig into the code to see what is does. I also don't have to go online and look at the module in Herd to see if a module is cross-platform or not. And it helps tools to maintain consistency and give you better error messages.

Adding it implicitly is certainly an option and I did look at that, but in the case of the compiler it might mean that it has to do a lot of work before finally finding out that "oh this module wasn't for me". Personally I like it a lot I can now type `ceylon compile \*` in the SDK and it will compile only the cross-platform and JVM modules skipping the JS ones automatically.

But we'll have to see how this works out, if people really find it too bothersome we'll probably just make it a warning or take it out entirely.

**Comment by luolong** [comment]
By "implicitly" I meant that when building a module for JVM, you implicitly add `native("jvm")` annotation to the module declaration and when building for JS backend, you implicitly annotate module with `native("js")`. 

This way, the annotation will always be there and always be right. That will be true of course only in case of new modules built after 1.2

This goes for the module being built. As for figuring out which of the dependencies are for which backend, you will  need to consult the repository for that in any case unless module import is annotated with `native(x)`, so this does not change anything....

**Comment by quintesse** [comment]
I know what implicitly means, but you can only figure that out by compiling all the code and compiling / downloading potentially all of its dependencies. That becomes so costly that it's of no use as a way to aid tooling. Of course if the only thing you're dealing with are compiled modules you won't notice.

> so this does not change anything....

Not true, you are now *obliged* to annotate your module when you are using native imports, so you at least know that *some* of them are native, or cross-platform, but at least it's obvious that the module you are looking at is not cross-platform. That's a lot of information at a glance.

**Comment by quintesse** [comment]
After some more consideration I've decided to close this issue, there's resistance against option 1. and option 2. doesn't really make a lot of sense (if you upload a native JS module it's relatively hard to also upload a JVM module because the compiler won't let you. So you'd have to make source changes between one compilation and the next and then upload them both. If you really *want* to upload broken code there are a myriad of ways of doing so of course)
