### ISSUE TITLE
Make doc links to Herd work across http/https

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-herd#239]
There must be a way to make it work in the `iframe` somehow.

**Comment by lucaswerkmeister** [comment]
Wouldn’t #238 make this unnecessary?

**Comment by FroMage** [comment]
Well, we'd have the same problem if we serve the docs from a different domain as the Herd UI, so it still has to be fixed ;)

**Comment by FroMage** [comment]
That page is now gone.
