### ISSUE TITLE
"Source Code" links in api documentation disappeared in 1.2.0

### ISSUE THREAD

**Issue by xkr47** [ceylon/ceylon-herd#240]
Compare upper right corner of these pages - notice how the "Source Code" link is missing in 1.2.0:

http://modules.ceylon-lang.org/repo/1/ceylon/language/1.1.0/module-doc/api/String.type.html
http://modules.ceylon-lang.org/repo/1/ceylon/language/1.2.0/module-doc/api/String.type.html

The list of attributes, methods etc also contained direct links to the source code for the respective elements in 1.1.0.

By modifying the version number in a source code url one can still access the source code of 1.2.0, so it's just the links that have disappeared.

**Comment by FroMage** [comment]
This is actually a build issue, and we've fixed it. It won't be fixed in Herd until the next upload, though. Thanks.

**Comment by gavinking** [comment]
This is a dupe of https://github.com/ceylon/ceylon-dist/issues/60. And I'm not sure it's fixed, FTR.
