### ISSUE TITLE
display information about dependencies on Module Info page

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-herd#242]
I would like to have info and links to dependencies on the Module Info page for a version of a module.

**Comment by FroMage** [comment]
Yeah, ATM it's on versions, since that's version-specific. We could add it to the module, but we'd have to take the latest version (like we do for docs).

**Comment by gavinking** [comment]
No I'm looking at the version page and I don't see it.

**Comment by gavinking** [comment]
FTR this was for a Java jar.

**Comment by gavinking** [comment]
OMG I'm such a liar. This is nonsense, dependencies _are_ shown on the module version page, even for Java jars. Not sure what I was smoking.

**Comment by FroMage** [comment]
Can I have some? :)
