### ISSUE TITLE
increase the number of modules per page/easier module discovery

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-herd#246]
There are still few enough modules that it's reasonable to flip through the list for discovery rather than relying on search, so it would be nice to:

1. Increase the number of modules per page (or, make it configurable), and
2. Keep the "next page" button from shifting horizontally, so the user can continue make mouse clicks without looking up & repositioning

**Comment by gavinking** [comment]
I agree. I thought it was a bit stingy with the page size.

**Comment by FroMage** [comment]
I bumped it to 20, but failed at finding a way to keep the page component of the same size as we move through pages.
