### ISSUE TITLE
make search case insensitive

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-herd#247]
Searching for "Collection" yields nothing, while "collection" gives you exactly what you want.

This affects mobile devices that like to capitalize the first character of whatever you type.

**Comment by FroMage** [comment]
Yes indeed.

**Comment by gavinking** [comment]
Even better: do camel hump matching :)

**Comment by FroMage** [comment]
@gavinking give me the HQL for camel hump matching, I'm taking PRs ;)

**Comment by FroMage** [comment]
Done (no camel hump)
