### ISSUE TITLE
"View docs" documentation links broken

### ISSUE THREAD

**Issue by xkr47** [ceylon/ceylon-herd#249]
Open https://herd.ceylon-lang.org/modules/fr.epardaud.iop and click "View docs"

Actual outcome: 404, url = https://**herd**.ceylon-lang.org/repo/1/fr/epardaud/iop/0.1/module-doc/index.html

If I instead click "Browse" -> module-doc -> index.html that instead leads me to the working url https://**modules**.ceylon-lang.org/repo/1/fr/epardaud/iop/0.1/module-doc/index.html i.e. same path but different hostname.

**Comment by FroMage** [comment]
Ah yes indeed, luckily that's only for really old modules. I'll fix it in the next release, thanks!

**Comment by FroMage** [comment]
Fixed.
