### ISSUE TITLE
Extract members from legacy JARs

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-herd#252]
It would be useful to have the list of member classes that exist in a JAR and store it in the DB just as we do for CARs. The `import-jar` command for example could then also suggest legacy modules for missing dependencies instead of only Ceylon modules as it does now.

**Comment by FroMage** [comment]
Good point, I don't really know why I did not do it for Jars… I'm _sure_ I must have had an evident great reason…

**Comment by quintesse** [comment]
Of course ;)

**Comment by FroMage** [comment]
Done.

**Comment by quintesse** [comment]
And for the existing JARs? Will we run some one-time upgrade script or something?

**Comment by FroMage** [comment]
Or wait until they're obsolete and rely on the new ones to fix this.
