### ISSUE TITLE
herd issue tracker shows 1 opened issue while github doesn't (actually no one issue opened)

### ISSUE THREAD

**Issue by LisiLisenok** [ceylon/ceylon-herd#261]
https://herd.ceylon-lang.org/modules/herd.asynctest/0.2.0
https://github.com/LisiLisenok/asyncTest/issues

**Comment by bjansen** [comment]
I think it was showing the PR (which is now closed).

**Comment by LisiLisenok** [comment]
@bjansen ok, maybe, now herd shows zero issues, so I think the issue can be closed?

**Comment by bjansen** [comment]
Yes.
