### ISSUE TITLE
Add possibility for release notes on a module version

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-herd#273]
I think it would be very useful to have the possibility of explaining what exactly was changed in a new version that gets uploaded. If the module has a link to a GitHub project set we could perhaps automatically set it to point to the `/releases` link, but it would be nice if it was a free field where people could add whatever documentation they want.

**Comment by gavinking** [comment]
I like the idea.

**Comment by FroMage** [comment]
What, like https://herd.ceylon-lang.org/modules/ceylon.net/1.2.2/changelog? ;)

**Comment by quintesse** [comment]
Hah, didn't even know that was there!

**Comment by luolong** [comment]
@FroMage the link above asks for my credentials ...

**Comment by FroMage** [comment]
Because you don't have permission to edit it. But it still works ;)
