### ISSUE TITLE
new category: plugins

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-herd#276]
Herd should have a category for plugins for the `ceylon` command. We already have `ceylon xxx-dart`, `ceylon swarm`, and `ceylon format`.

**Comment by gavinking** [comment]
And I think `java2ceylon` works as a command plugin too, though that appears to be completely undocumented...

**Comment by gavinking** [comment]
It also seems that `ceylon bootstrap` and perhaps even `ceylon test` live in Herd. Is that right?

**Comment by quintesse** [comment]
Both `ceylon bootstrap` and `ceylon test` are built-in commands.

**Comment by FroMage** [comment]
Done: https://herd.ceylon-lang.org/categories/Command-line-plugins

**Comment by gavinking** [comment]
Thanks. FTR, the URL is <https://herd.ceylon-lang.org/categories/Command-line%20plugins>.
