### ISSUE TITLE
1.3.2 modules are missing from Herd Maven repo

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-herd#286]
@FroMage none of the 1.3.2 release modules actually exist in the Herd maven repo.

**Comment by gavinking** [comment]
Oh. Actually I suppose this is intentional, since these modules are now available in Maven Central. Is that right, @FroMage?

**Comment by FroMage** [comment]
No, it's a duplicate of #283 which is a browsing issue, but Maven finds the modules alright. See https://herd.ceylon-lang.org/maven/1/org/ceylon-lang

**Comment by gavinking** [comment]
OK, sorry for the noise.
