### ISSUE TITLE
ceylon-herd not installing correctly(missing play modules)

### ISSUE THREAD

**Issue by sotona-** [ceylon/ceylon-herd#287]
When i running "play dependencies" command, play can't  download:
- http://www.playframework.org/modules/repo/gravatar/1.0.2/dependencies.yml
- http://www.playframework.org/modules/repo/db/1.1.1/dependencies.yml
files(404 error) and can't install gravatar and db modules.

**Comment by FroMage** [comment]
Hi,

I seems they nuked their Maven repo :(

I've added the two modules to git, if you pull and retry it should work.

**Comment by sotona-** [comment]
Hi, thank you, but not working.
Play tries to find modules in play/modules directory. See log.
[ch2.txt](https://github.com/ceylon/ceylon-herd/files/1080346/ch2.txt)

**Comment by FroMage** [comment]
Ah, I see. It worked for me because they're already in my Maven repo. I think you can start Herd, though, because they are available. Let me know if it works, and I'll update the instructions.

**Comment by sotona-** [comment]
It works. Thanks!

**Comment by FroMage** [comment]
Cool!
