### ISSUE TITLE
Page is trying to load from an unauthenticated source

### ISSUE THREAD

**Issue by cloudvapor** [ceylon/ceylon-herd#290]
When I visit https://modules.ceylon-lang.org/repo/1/ceylon/language/1.1.0/module-doc/api/OptionalAnnotation.type.html, Chrome warns that the page is trying to load from an unauthenticated source (http://fonts.googleapis.com/css?family=Source+Sans+Pro|Inconsolata|Inconsolata:700|PT+Sans|PT+Sans). I think that this should be easily fixed by changing to use TLS/SSL.

**Comment by FroMage** [comment]
It's fixed in newer releases of the module: https://modules.ceylon-lang.org/repo/1/ceylon/language/1.3.2/module-doc/api/OptionalAnnotation.type.html

In any case, this is not a Herd issue but a documentation generator issue. Thanks for reporting anyway.
